CREATE DATABASE IF NOT EXISTS `db_medidor_agua`;

CREATE TABLE usuario(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE registro(
    idVivienda BIGSERIAL NOT NULL PRIMARY KEY,
    idUsuario BIGINT NOT NULL REFERENCES usuario(id),
    direccion VARCHAR(150) NOT NULL,
    mz VARCHAR(50) NOT NULL,
    villa VARCHAR(50) NOT NULL,
    imagen VARCHAR(150) NOT NULL,
    lectura  NUMERIC(10,2) NOT NULL,
    coordenadas VARCHAR(150) NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE tarea(
    idTarea BIGSERIAL NOT NULL PRIMARY KEY,
    idUsuario BIGINT NOT NULL REFERENCES usuario(id),
    titulo VARCHAR(50) NOT NULL,
    descripcion VARCHAR(150) NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);